### PR TITLE
feat: Integrate Arweave into gallery page

### PR DESCRIPTION
**Pull request by johnletey**
Don't know how to get the `reputation` and `stake` for a trading post - I'd assume this would be from the DAO?

### CODE REVIEW

**Comment by t8** [comment]
Reputation will be calculated on the frontend, and stake will be an ArQL call. 

CC @zorbyte (how to get stake?)

**Comment by johnletey** [comment]
@t8 What exactly is this "calculation". Let's chat in discord 😄

**Comment by t8** [comment]
Here is my proposed reputation calculation:
image

This is completely up for discussion, and I'm interested to hear others' opinions on this!

CC @samcamwilliams

**Comment by johnletey** [comment]
@ anyone that's following along: Just switched over from using ArQL to the new Arweave GraphQL endpoint.

There might be some merge conflicts once #23 is merged (dependencies etc), but we'll cross that bridge when we get there 😅

@martonlederer Would love some help with infinite loading and polishing the design 😄

**Comment by t8** [comment]
I propose that we merge this before merging #23 and fix merge conflicts from that PR.

I also created the dev branch for the purpose of finishing MVP 1 before merging into master. (Master has a visually functioning demo at this point in time)

**Comment by johnletey** [comment]
I've gone ahead and merged this.

Still need to pull the `reputation` and `stake` for a trading post.

The design should also be updated, with infinite loading as well 😄

**Pull request merged**
