### PR TITLE
feat: Export GraphQL queries

### PR DESCRIPTION
**Pull request by martonlederer**
- [x] Add `.graphql`/ `.gql` files loading support
- [x] Refactor queries

### CODE REVIEW

**Comment by martonlederer** [comment]
Ready for review. @t8 @johnletey you both should take a look at this to see how I updated the `query()` function

**Comment by t8** [comment]
I also think we should merge #24 & #27 before merging this. That way, we can add the queries from those PRs here as well.

**Comment by martonlederer** [comment]
Alright

**Review by johnletey — APPROVED** [review]
@martonlederer Wonderful job on this 🙌🏻

I did a bit of local testing, and the query for the `/gallery` page wasn't quite working.

But I've gone ahead and fixed that for ya 😄

LGTM 🚀

**Comment by t8** [comment]
Receiving this error when attempting to view the trading posts page: 
image

CC @martonlederer 

Note: I had run `yarn` and restarted the server prior, so all dependencies were present at the time of seeing that.

**Review by divy-work — APPROVED** [review]
Great job

**Comment by johnletey** [comment]
@t8 That error was an issue with merging in changes from #30 😄

I've gone ahead and fixed the issue!

**Comment by t8** [comment]
Receiving this error from the route: `http://localhost:3000/tokens`

image

The other pages load perfectly, so nice job!

**Comment by johnletey** [comment]
Ight @t8, investigating 🧐😂

**Comment by johnletey** [comment]
@t8 Fixed it on my end, lmk if that did the trick 😄

**Pull request merged**
