### PR TITLE
Simplify and refactor (typescript)

### PR DESCRIPTION
**Pull request by martonlederer**
- [x] Move all types/interfaces to `types.ts` (everything will be easier to manage, no need to declare interfaces each occasion a new variable is created)
- [x] Recode service worker to use Typescript
- [x] Modify svelte-prettier config (script-html-style layout, strict html, etc.)
- [x] Add graphql (`.graphql` and `.gql`) type declarations (fixes errors in VSCode)
- [x] Remove Sapper type declarations and update Sapper version (this version includes it's own declarations)

### CODE REVIEW

**Comment by martonlederer** [comment]
This can be merged right away if @t8 approves

**Review by t8 — COMMENTED** [review]
Trading functionality should still be tested on the **test** contract, but everything else looks good to me! I tested all other pages & functionality on each.

**Comment by martonlederer** [comment]
@divy-work or @johnletey if you could test what @t8 mentioned, that'd be great

**Review by johnletey — APPROVED** [review]
@martonlederer Can confirm that trades work!!!

LGTM

**Pull request merged**
