### PR TITLE
feat: caching

### PR DESCRIPTION
**Pull request by johnletey**

### CODE REVIEW

**Review by t8 — DISMISSED** [review]
LGTM, but why is the build failing in CI?

**Comment by martonlederer** [comment]
I'll check that @t8 and also will add some loadings

**Comment by t8** [comment]
Is it fair to assume we'll be integrating CacheWeave support instead of this solution, @johnletey?

**Comment by johnletey** [comment]
@t8 All caching is handled in the `lib` 😄

I have transferred the lib to use CacheWeave though! (https://github.com/useverto/lib/commit/3d155a6cb08832247b9a8ce1d1cd2334f179c8df)

**Comment by t8** [comment]
Got it. Sounds good!

**Review by t8 — APPROVED** [review]

**Comment by johnletey** [comment]
Wuhuu 🥳 Finally fixed the build 🙌🏻

**Review by t8 — APPROVED** [review]
LGTM

Amazing work!

**Pull request merged**
